### ISSUE TITLE
not able to use the public web version anymore

### ISSUE THREAD

**Issue by NargiT** [giranm/pd-live-react#479]
Hello,

I don't know why I cannot access your application anymore. This is the error I get every time I try. it was working fine before. 

![image](https://github.com/giranm/pd-live-react/assets/3153333/db0984aa-6af7-446f-820d-af6bd24adca0)

for some reason de `bearer is null`
![image](https://github.com/giranm/pd-live-react/assets/3153333/95771a55-dff7-447a-bd86-efd2f88b48ca)

**Comment by martindstone** [comment]
Hi there,

PagerDuty recently updated the rules for OAuth flow and this repo isn't maintained by PagerDuty. Could you try the maintained app at https://pagerduty.github.io/pd-live-react instead and let us know if that works for you? Thanks!

**Comment by NargiT** [comment]
It works ! thank you, I will switch to this version as it provided by pager duty. Thanks !
