### ISSUE TITLE
[Bug] Search Issues

### ISSUE THREAD

**Issue by jmpoastUP** [giranm/pd-live-react#86]
I can't filter on anything past the first few parts of the title when searching.

for example:

PRODUCTION DEGRADED: ptc0231.xl000_ptcprd085.wla.tla.uprr.com (CHK_LOG) - LOGS is degraded - ptcprd085.wla.tla.uprr.com - Workload Job PTC0231.XL000 is in FAILURE status

searching for production or degraded returns this item, trying to filter on anything else (like logs, or workload) returns nothing.

**Comment by giranm** [comment]
This has been patched under PR #129 and merged into develop - closing issue.
