### ISSUE TITLE
[Bug] Row selection selects row number not incident

### ISSUE THREAD

**Issue by jmpoastUP** [giranm/pd-live-react#92]
When checking a row it appears to leave the check on the row number and doesn't move with the incident when a new incident comes in and the selected incident gets moved to a different row.

e.x. 

   incident a
x incident b
   incident c

If I select the row that incident b is currently on, and we get a new incident in, incident a will be selected instead

   incident d
x incident a
   incident b
   incident c

**Comment by giranm** [comment]
On initial triage, it looks like this is due to the fact that we are using `react-window` for virtualisation.
Will need to further investigate solutions to this, potentially additional hooks to ensure the correct rows keep selection.
